Speed up dx
eastgenomics/Genetics_Ark pull request #78
Opened 2024-06-20 11:26 UTC by corbin-chris

Changes:
Parallelising dxpy searches and removing redundant API calls
Closes #73 #62 

Test set-up:
Ran latest-version genetics-ark-cron code (with jq manually installed), and looked at outputs of the find_dx_data.py
Compared to the output from find_dx_data.py when running genetics-ark-cron:speed_up_dx, keeping the rest of the containers the same.

Test results:
Updated code runs 10x faster (on comparison run, 65.9 seconds versus 1100.8 seconds)
Nothing gets output to the cron error logs
Both the updated code and the current code, find the same number of file entries (cat dx_002_bams.json | jq '.BAM[][].idx_name' | wc), and no empty indices with 'jq '.BAM[][].idx_name''
The dx_002_bams.json file is the same size for updated and current code. dx_missing_bam.json is trivially different (584623 for new, 584149 for old).

2024-06-20 11:26 UTC, pep8speaks commented
Hello @corbin-chris! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`cron/find_dx_data.py`](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py):

> [Line 146:80](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L146): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 230:46](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L230): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\.'
> [Line 230:56](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L230): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\.'
> [Line 358:45](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L358): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\Z'
> [Line 358:78](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L358): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\Z'
> [Line 358:80](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L358): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 395:80](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L395): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 397:80](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L397): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)

2024-06-20 11:35 UTC, Yu-jinKim requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78)* status: all files reviewed, 1 unresolved discussion (waiting on @corbin-chris and @jethror1)

___
*[`cron/find_dx_data.py` line 396 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78#-O-pQPEq0ELF3M4a1ze9:-O-pQPEq0ELF3M4a1zeA:b-sam2tc) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L396)):*
> ```Python
>             if len(cnv_index) > 1:
>                 # very occasionally there's more than one index file - use the first
>                 print(
> ```

what's the purpose of the print here?


<!-- Sent from Reviewable.io -->

2024-06-20 11:42 UTC, corbin-chris reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1 and @Yu-jinKim)

___
*[`cron/find_dx_data.py` line 396 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78#-O-pQPEq0ELF3M4a1ze9:-O-pRnNFBVhfMG_k-Y2V:bv5wwt0) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L396)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

what's the purpose of the print here?
</blockquote></details>

I thought it was worth logging in case the selected index ends up being out-of-date or incorrect, and the end-user complains of problems viewing the affected file.  


<!-- Sent from Reviewable.io -->

2024-06-20 12:14 UTC, jethror1 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris and @Yu-jinKim)

___
*[`cron/find_dx_data.py` line 241 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78#-O-pSeny5_1X-12IM2nN:-O-pSeny5_1X-12IM2nO:b-3202du) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L241)):*
This is going to result in 2*n projects worth of list comps across the massive return of all bam details, which I assume is going to be fairly costly (i.e for 800 projects that's 1600 iterations over the whole list of I'd assume many thousands of bams and index).

I'd instead consider doing an initial `groupby()` with the project ID to split the BAMs to lists of dicts by their project, then iterate over this and get the project name by ID from `project_id_to_name` dict. You can then also do a group

 Here's a tiny example (although with just one project, so we get a dict with one mapping of project: files):
```
>>> from itertools import groupby
>>> files = list(dxpy.find_data_objects(
    project=dxpy.WORKSPACE_ID, limit=2, classname='file',
    describe={'fields': {'archivalState': True, 'folder': True, 'name': True}}
))
>>> files
[{'project': 'project-GgQJfvQ4bjXByF6Pj3YB5Fx5',
  'id': 'file-GkkzQ004bjX4G5z5vGPPPVVx',
  'describe': {'id': 'file-GkkzQ004bjX4G5z5vGPPPVVx',
   'name': 'README.md',
   'folder': '/',
   'archivalState': 'live'}},
 {'project': 'project-GgQJfvQ4bjXByF6Pj3YB5Fx5',
  'id': 'file-GgQQkJ047YfkG6v908X3Q2YQ',
  'describe': {'id': 'file-GgQQkJ047YfkG6v908X3Q2YQ',
   'name': 'job-GgQQK584bjXK5K6y49x3gx6b_summary.tsv',
   'folder': '/',
   'archivalState': 'live'}}]

# groupby these by project
>>> {k: list(v) for k, v in groupby(files, lambda x: x['project'])}
{'project-GgQJfvQ4bjXByF6Pj3YB5Fx5': [{'project': 'project-GgQJfvQ4bjXByF6Pj3YB5Fx5',
   'id': 'file-GkkzQ004bjX4G5z5vGPPPVVx',
   'describe': {'id': 'file-GkkzQ004bjX4G5z5vGPPPVVx',
    'name': 'README.md',
    'folder': '/',
    'archivalState': 'live'}},
  {'project': 'project-GgQJfvQ4bjXByF6Pj3YB5Fx5',
   'id': 'file-GgQQkJ047YfkG6v908X3Q2YQ',
   'describe': {'id': 'file-GgQQkJ047YfkG6v908X3Q2YQ',
    'name': 'job-GgQQK584bjXK5K6y49x3gx6b_summary.tsv',
    'folder': '/',
    'archivalState': 'live'}}]}
```

If you then iterate over this dict of project: files and want to then split these by bam and bai in the small per project sub lists, you can either do 2 list comps here, or another groupby on the filename suffix would work either:

```
from pathlib import Path

>>> {k: list(v) for k, v in groupby(project_grouped['project-GgQJfvQ4bjXByF6Pj3YB5Fx5'], lambda x: Path(x['describe']['name']).suffix)}

{'.md': [{'project': 'project-GgQJfvQ4bjXByF6Pj3YB5Fx5',
   'id': 'file-GkkzQ004bjX4G5z5vGPPPVVx',
   'describe': {'id': 'file-GkkzQ004bjX4G5z5vGPPPVVx',
    'name': 'README.md',
    'folder': '/',
    'archivalState': 'live'}}],
 '.tsv': [{'project': 'project-GgQJfvQ4bjXByF6Pj3YB5Fx5',
   'id': 'file-GgQQkJ047YfkG6v908X3Q2YQ',
   'describe': {'id': 'file-GgQQkJ047YfkG6v908X3Q2YQ',
    'name': 'job-GgQQK584bjXK5K6y49x3gx6b_summary.tsv',
    'folder': '/',
    'archivalState': 'live'}}]}

```

n.b. I haven't actually timed this, but it should be faster because less iterating

now the suffix will become the key with all the file describe objects as a list



_Code quote:_
```Python
        project_bams = [x for x in bams if x["project"] == project_id]
        project_idxs = [x for x in idxs if x["project"] == project_id]
```


<!-- Sent from Reviewable.io -->

2024-06-20 12:40 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris and @Yu-jinKim)

___
*[`cron/find_dx_data.py` line 241 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78#-O-pSeny5_1X-12IM2nN:-O-pdm2j60-6ZCHe8cuD:b-jgb4ez) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L241)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

This is going to result in 2*n projects worth of list comps across the massive return of all bam details, which I assume is going to be fairly costly (i.e for 800 projects that's 1600 iterations over the whole list of I'd assume many thousands of bams and index).

I'd instead consider doing an initial `groupby()` with the project ID to split the BAMs to lists of dicts by their project, then iterate over this and get the project name by ID from `project_id_to_name` dict. You can then also do a group

 Here's a tiny example (although with just one project, so we get a dict with one mapping of project: files):
```
>>> from itertools import groupby
>>> files = list(dxpy.find_data_objects(
    project=dxpy.WORKSPACE_ID, limit=2, classname='file',
    describe={'fields': {'archivalState': True, 'folder': True, 'name': True}}
))
>>> files
[{'project': 'project-GgQJfvQ4bjXByF6Pj3YB5Fx5',
  'id': 'file-GkkzQ004bjX4G5z5vGPPPVVx',
  'describe': {'id': 'file-GkkzQ004bjX4G5z5vGPPPVVx',
   'name': 'README.md',
   'folder': '/',
   'archivalState': 'live'}},
 {'project': 'project-GgQJfvQ4bjXByF6Pj3YB5Fx5',
  'id': 'file-GgQQkJ047YfkG6v908X3Q2YQ',
  'describe': {'id': 'file-GgQQkJ047YfkG6v908X3Q2YQ',
   'name': 'job-GgQQK584bjXK5K6y49x3gx6b_summary.tsv',
   'folder': '/',
   'archivalState': 'live'}}]

# groupby these by project
>>> {k: list(v) for k, v in groupby(files, lambda x: x['project'])}
{'project-GgQJfvQ4bjXByF6Pj3YB5Fx5': [{'project': 'project-GgQJfvQ4bjXByF6Pj3YB5Fx5',
   'id': 'file-GkkzQ004bjX4G5z5vGPPPVVx',
   'describe': {'id': 'file-GkkzQ004bjX4G5z5vGPPPVVx',
    'name': 'README.md',
    'folder': '/',
    'archivalState': 'live'}},
  {'project': 'project-GgQJfvQ4bjXByF6Pj3YB5Fx5',
   'id': 'file-GgQQkJ047YfkG6v908X3Q2YQ',
   'describe': {'id': 'file-GgQQkJ047YfkG6v908X3Q2YQ',
    'name': 'job-GgQQK584bjXK5K6y49x3gx6b_summary.tsv',
    'folder': '/',
    'archivalState': 'live'}}]}
```

If you then iterate over this dict of project: files and want to then split these by bam and bai in the small per project sub lists, you can either do 2 list comps here, or another groupby on the filename suffix would work either:

```
from pathlib import Path

>>> {k: list(v) for k, v in groupby(project_grouped['project-GgQJfvQ4bjXByF6Pj3YB5Fx5'], lambda x: Path(x['describe']['name']).suffix)}

{'.md': [{'project': 'project-GgQJfvQ4bjXByF6Pj3YB5Fx5',
   'id': 'file-GkkzQ004bjX4G5z5vGPPPVVx',
   'describe': {'id': 'file-GkkzQ004bjX4G5z5vGPPPVVx',
    'name': 'README.md',
    'folder': '/',
    'archivalState': 'live'}}],
 '.tsv': [{'project': 'project-GgQJfvQ4bjXByF6Pj3YB5Fx5',
   'id': 'file-GgQQkJ047YfkG6v908X3Q2YQ',
   'describe': {'id': 'file-GgQQkJ047YfkG6v908X3Q2YQ',
    'name': 'job-GgQQK584bjXK5K6y49x3gx6b_summary.tsv',
    'folder': '/',
    'archivalState': 'live'}}]}

```

n.b. I haven't actually timed this, but it should be faster because less iterating

now the suffix will become the key with all the file describe objects as a list
</blockquote></details>

^ I tried to write something to simulate this with semi realistic amounts of data (800 projects @ 40 describe objects each), and the groupby works out to be ~1000 times faster if I got it correct


<!-- Sent from Reviewable.io -->

2024-06-20 12:48 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris and @Yu-jinKim)

___
*[`cron/find_dx_data.py` line 241 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78#-O-pSeny5_1X-12IM2nN:-O-pg7TuAGq-44YC9eXN:b-cwxx9m) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L241)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

^ I tried to write something to simulate this with semi realistic amounts of data (800 projects @ 40 describe objects each), and the groupby works out to be ~1000 times faster if I got it correct
</blockquote></details>

well not actually that fast since it still needs to iterate over each project set of data, but still like ~0.1s vs ~4s


<!-- Sent from Reviewable.io -->

2024-06-20 14:08 UTC, corbin-chris reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`cron/find_dx_data.py` line 241 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78#-O-pSeny5_1X-12IM2nN:-O-pyQqnEJUgQ73ZrLq4:b7551lt) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/4569d7588d4239a121594b3a3f5016efbef3d9dc/cron/find_dx_data.py#L241)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

well not actually that fast since it still needs to iterate over each project set of data, but still like ~0.1s vs ~4s
</blockquote></details>

Done Changed it for some speed improvement - it's now running ~30 seconds


<!-- Sent from Reviewable.io -->

2024-06-21 16:47 UTC, jethror1 approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78)* status: all files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2024-06-21 16:48 UTC, jethror1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78)* status: all files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2024-06-21 16:48 UTC, jethror1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/78)* status: all files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2024-06-21 16:49 UTC, merged